### ISSUE TITLE
Acerca del Proyecto 

### ISSUE THREAD

**Issue by FraGoTe** [AngelFQC/museaMoz#14]
Tienes pensado hacer una versión 100% web que incluya mapas y que utilice un apropiado backend?

**Comment by AngelFQC** [comment]
Sí, de hecho, en los datos de algunos museos en los JSON ya tiene las coordenadas

**Comment by FraGoTe** [comment]
Tienes algunas referencias de proyectos como este?

**Comment by AngelFQC** [comment]
Como aplicación web no, pero sí he visto que hay para Android y iOS
