### ISSUE TITLE
Validar existencia de datos en Contacto

### ISSUE THREAD

**Issue by juaneladio** [AngelFQC/museaMoz#7]
Cuando un museo no tiene ningún dato de Contacto, se muestra el título Contacto sin nada debajo. Lo mejor sería ocultar totalmente esa sección.

Quizá este cambio afecte a todos los bloques listados en un museo.

Caso de prueba: Amazonas - La Jalca Grande - Museo de exhibición.

**Comment by AngelFQC** [comment]
Solucionado.
Ahora no muestra la sección de contacto cuando en esa sección no hay datos.
